name: Warzone CI

on:
  push:
    branches: [ master, dev, qa ]
  pull_request:
    branches: [ master, dev, qa ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.2'
          distribution: 'temurin'
      - name: Build WarZone Game
        run: mvn install
      - name: Run WarZone Tests
        run: mvn test
      - name: Javadoc Generation
        run: mvn javadoc:javadoc